// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jtwhwcchuvyijgpgnjmo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imp0d2h3Y2NodXZ5aWpncGduam1vIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzk5MDc2MjQsImV4cCI6MjA1NTQ4MzYyNH0.6gFc0YgyhbQGSXGBglXozEtFhizd6EZi_d8ELjNKFMU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);